services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: moneylender_apache
    restart: always
    volumes:
      - .:/var/www/html/
      - ./config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./config/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '80:80'
    networks:
      - moneylender
    environment:
      TZ: "America/Maceio"
  mysql:
    container_name: moneylender_mysql
    restart: always
    image: mysql:latest
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "America/Maceio"
    ports:
      - '3306:3306'
    networks:
      - moneylender
networks:
  moneylender:
    driver: bridge
