version: '3'

services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: moneylender_apache
    restart: always
    volumes:
      - .:/var/www/html/
      - ./config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./config/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '2020:80'
    networks:
      - moneylender
    environment:
      TZ: "America/Maceio"
  mysql:
    container_name: moneylender_mysql
    restart: always
    image: mysql:latest
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: moneylender@!#
      MYSQL_DATABASE: moneylender
      MYSQL_PASSWORD: 123456
      TZ: "America/Maceio"
    ports:
      - '2200:3306'
    networks:
      - moneylender
networks:
  moneylender:
    driver: bridge
